apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}
  labels:
    {{- include "app2.labels" . | nindent 4 }}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      {{- include "app2.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app2.labels" . | nindent 8 }}
    spec:
      containers:
      - name: appjava
      {{- if .Values.image}}
        image: tienphuoc/javaapp:857cfb5
      {{- else}}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
      {{- end}}
        ports:
        - containerPort: 8080
        env:
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: app-db-secret
              key: DB_URL

        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-db-secret
              key: DB_USERNAME

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-db-secret
              key: DB_PASSWORD
